# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# LOCAL KIND ONLY. The NodePort Services in this file are reachable only on
# the developer's laptop, because kind maps them to 127.0.0.1. Do NOT apply
# this file to a shared or cloud cluster: there a NodePort is reachable from
# the whole network. Cluster deployments use ClusterIP + kubectl port-forward.
# NodePorts for DataHub. The chart's gms/frontend services are ClusterIP; these
# expose them on the node ports the kind cluster maps to the host
# (cluster.yaml: GMS host 8080 -> 30808, frontend host 9002 -> 30902), so the
# host reaches the DataHub UI at localhost:9002 and the GMS/MCP API at
# localhost:8080 with no port-forward. Selectors match the datahub chart
# (release instance 'datahub').
apiVersion: v1
kind: Service
metadata:
  name: datahub-gms-nodeport
  namespace: datahub
  labels:
    app.kubernetes.io/name: datahub-gms
    app.kubernetes.io/managed-by: account-demo-local
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: datahub-gms
    app.kubernetes.io/instance: datahub
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30808
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-frontend-nodeport
  namespace: datahub
  labels:
    app.kubernetes.io/name: datahub-frontend
    app.kubernetes.io/managed-by: account-demo-local
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: datahub-frontend
    app.kubernetes.io/instance: datahub
  ports:
    - name: http
      port: 9002
      targetPort: http
      nodePort: 30902
